// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace MLNETWorkshopML.Model
{
    public class ModelInput
    {
        [ColumnName("product_name"), LoadColumn(0)]
        public string Product_name { get; set; }


        [ColumnName("category"), LoadColumn(1)]
        public string Category { get; set; }


        [ColumnName("retail_price"), LoadColumn(2)]
        public float Retail_price { get; set; }


        [ColumnName("description"), LoadColumn(3)]
        public string Description { get; set; }


        [ColumnName("brand"), LoadColumn(4)]
        public string Brand { get; set; }


    }
}
